package view;


import util.FBDBConnect;
import model.TableModel;
import model.feedback;
import service.feedbacksql;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SRI
 */
public class admin_view extends javax.swing.JFrame {

    int x,feedbackId=-1;
    
    JFrame frame;
    
    /**
     * Creates new form admin_view
     */
    public admin_view() {
        initComponents();
         this.setLocationRelativeTo(null);
         displayFeedbackTable();
         prathapicusID.setText("");
    }
    
    public void displayFeedbackTable(){
    
        feedbacksql feed = new feedbacksql();
        ArrayList<feedback> feedList = feed.feedbackList();
        
        String[] colNames = {"Feedback ID","Customer ID","Phone Number","Category","Feedback","Rating"};
        Object[][]rows= new Object[feedList.size()][6];
        
        for(int i=0;i<feedList.size();i++){
            
            rows[i][0] = feedList.get(i).getId();
            rows[i][1] = feedList.get(i).getCustomerId();
            rows[i][2] = feedList.get(i).getPhone();
            rows[i][3] = feedList.get(i).getCategory();
            rows[i][4] = feedList.get(i).getOption();
            rows[i][5] = feedList.get(i).getRating();
            
        }
        
        TableModel tbm= new TableModel(rows,colNames);
        feedbackTb.setModel(tbm);
        
        feedbackTb.setShowGrid(true);
        feedbackTb.setGridColor(Color.black);
        
    }
    
    public void customerFeedbackTable(int id){
    
        feedbacksql feed = new feedbacksql();
        ArrayList<feedback> feedList = feed.feedbackListCustomer(id);
        
        String[] colNames = {"Feedback ID","Customer ID","Phone Number","Category","Feedback","Rating"};
        Object[][]rows= new Object[feedList.size()][6];
        
        for(int i=0;i<feedList.size();i++){
            
            rows[i][0] = feedList.get(i).getId();
            rows[i][1] = feedList.get(i).getCustomerId();
            rows[i][2] = feedList.get(i).getPhone();
            rows[i][3] = feedList.get(i).getCategory();
            rows[i][4] = feedList.get(i).getOption();
            rows[i][5] = feedList.get(i).getRating();
            
        }
        
        TableModel tbm= new TableModel(rows,colNames);
        feedbackTb.setModel(tbm);
        
        feedbackTb.setShowGrid(true);
        feedbackTb.setGridColor(Color.black);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prathapijLabel1 = new javax.swing.JLabel();
        prathapijLabel2 = new javax.swing.JLabel();
        prathapijButton1 = new javax.swing.JButton();
        prathapijButton2 = new javax.swing.JButton();
        prathapijScrollPane1 = new javax.swing.JScrollPane();
        feedbackTb = new javax.swing.JTable();
        prathapijButton3 = new javax.swing.JButton();
        prathapicusID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prathapijLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        prathapijLabel1.setText(" CUSTOMER FEEDBACK");

        prathapijLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel2.setText(" Customer ID :");

        prathapijButton1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton1.setForeground(new java.awt.Color(160, 31, 38));
        prathapijButton1.setText(" SEARCH");
        prathapijButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prathapijButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapijButton1ActionPerformed(evt);
            }
        });

        prathapijButton2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton2.setText(" GENERATE REPORTS");
        prathapijButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        feedbackTb.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        feedbackTb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Feedback ID", "Customer ID", "Customer Phone Number", "Category", "Feedback", "Rating"
            }
        ));
        feedbackTb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feedbackTbMouseClicked(evt);
            }
        });
        prathapijScrollPane1.setViewportView(feedbackTb);
        if (feedbackTb.getColumnModel().getColumnCount() > 0) {
            feedbackTb.getColumnModel().getColumn(1).setPreferredWidth(100);
            feedbackTb.getColumnModel().getColumn(2).setPreferredWidth(100);
            feedbackTb.getColumnModel().getColumn(3).setPreferredWidth(100);
            feedbackTb.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        prathapijButton3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton3.setForeground(new java.awt.Color(28, 47, 123));
        prathapijButton3.setText("Delete Feedback");
        prathapijButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapijButton3ActionPerformed(evt);
            }
        });

        prathapicusID.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        prathapicusID.setPreferredSize(new java.awt.Dimension(6, 30));
        prathapicusID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prathapicusIDKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(prathapijLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prathapijScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(prathapijLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(prathapicusID, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(prathapijButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(prathapijButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(prathapijButton3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prathapijLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(prathapijButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(prathapicusID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prathapijButton1))
                    .addComponent(prathapijLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(prathapijScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prathapijButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prathapijButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapijButton1ActionPerformed
        if(prathapicusID.getText().equals("")){
            JOptionPane.showMessageDialog(frame, "Please Enter Customer ID!");
        }else{
            customerFeedbackTable(Integer.parseInt(prathapicusID.getText().toString()));
        }
    }//GEN-LAST:event_prathapijButton1ActionPerformed

    private void feedbackTbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feedbackTbMouseClicked
        int rowIndex = feedbackTb.getSelectedRow();
        
        feedbackId = Integer.parseInt(feedbackTb.getValueAt(rowIndex, 0).toString());
    }//GEN-LAST:event_feedbackTbMouseClicked

    private void prathapijButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapijButton3ActionPerformed
        if(feedbackId == -1){
            JOptionPane.showMessageDialog(frame, "Please Select Feedback!");
        }else{
            Connection connection;
            PreparedStatement preparedStatement;
		
		try {
			connection = FBDBConnect.getDBConnection();
			
                        //insert value
                        preparedStatement = connection.prepareStatement("DELETE FROM feedback where feedbackId=?");
                        preparedStatement.setInt(1, feedbackId);
                        preparedStatement.execute();
                        preparedStatement.close();
                        connection.close();
                        
                        displayFeedbackTable();
                        
                        JOptionPane.showMessageDialog(frame, "Feedback Delete Successful!");
                        
                    }catch (ClassNotFoundException | SQLException  e) {
                    System.out.println(e.getMessage());
		}
        }
    }//GEN-LAST:event_prathapijButton3ActionPerformed

    private void prathapicusIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prathapicusIDKeyReleased
        try {
            x = Integer.parseInt(prathapicusID.getText());
        } catch (NumberFormatException nfe) {
            prathapicusID.setText("");
        }
    }//GEN-LAST:event_prathapicusIDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable feedbackTb;
    private javax.swing.JTextField prathapicusID;
    private javax.swing.JButton prathapijButton1;
    private javax.swing.JButton prathapijButton2;
    private javax.swing.JButton prathapijButton3;
    private javax.swing.JLabel prathapijLabel1;
    private javax.swing.JLabel prathapijLabel2;
    private javax.swing.JScrollPane prathapijScrollPane1;
    // End of variables declaration//GEN-END:variables
}
