package view;


import java.awt.Color;
import static java.awt.Color.yellow;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import util.*;
import util.FBDBConnect;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SRI
 */
public class enter_feedback extends javax.swing.JFrame {

    int x;
    
    Color myWhite = new Color(240, 240, 240);
    
    int rating=0;
    
    JFrame frame;
    /**
     * Creates new form enter_feedback
     */
    public enter_feedback() {
        initComponents();
        this.setLocationRelativeTo(null);
        prathapicusTxt.setText("");
        optionTxt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prathapijLabel1 = new javax.swing.JLabel();
        prathapijLabel2 = new javax.swing.JLabel();
        prathapijLabel3 = new javax.swing.JLabel();
        prathapicusTxt = new java.awt.TextField();
        prathapijLabel4 = new javax.swing.JLabel();
        prathapijLabel5 = new javax.swing.JLabel();
        prathapijButton1 = new javax.swing.JButton();
        prathapijScrollPane1 = new javax.swing.JScrollPane();
        optionTxt = new javax.swing.JTextArea();
        prathapijButton2 = new javax.swing.JButton();
        prathapicatBox = new javax.swing.JComboBox<>();
        prathapirating2 = new javax.swing.JToggleButton();
        prathapirating3 = new javax.swing.JToggleButton();
        prathapirating4 = new javax.swing.JToggleButton();
        prathapirating5 = new javax.swing.JToggleButton();
        prathapirating1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prathapijLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        prathapijLabel1.setText(" ENTER FEEDBACK");

        prathapijLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel2.setText(" Customer ID :");

        prathapijLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel3.setText(" Select Category :");

        prathapicusTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        prathapicusTxt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        prathapicusTxt.setForeground(new java.awt.Color(0, 0, 0));
        prathapicusTxt.setPreferredSize(new java.awt.Dimension(6, 30));
        prathapicusTxt.setText(" ");
        prathapicusTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                prathapicusTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                prathapicusTxtFocusLost(evt);
            }
        });
        prathapicusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapicusTxtActionPerformed(evt);
            }
        });
        prathapicusTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prathapicusTxtKeyReleased(evt);
            }
        });

        prathapijLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel4.setText("Rating :");

        prathapijLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel5.setText("Opinion :");

        prathapijButton1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton1.setForeground(new java.awt.Color(28, 47, 123));
        prathapijButton1.setText(" SEND FEEDBACK");
        prathapijButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prathapijButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapijButton1ActionPerformed(evt);
            }
        });

        optionTxt.setColumns(20);
        optionTxt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        optionTxt.setRows(5);
        optionTxt.setText(" .");
        optionTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                optionTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                optionTxtFocusLost(evt);
            }
        });
        prathapijScrollPane1.setViewportView(optionTxt);

        prathapijButton2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton2.setText(" MAIN MENU");
        prathapijButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapijButton2MouseClicked(evt);
            }
        });

        prathapicatBox.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        prathapicatBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Select ~", "Suggestion", "Something is not correct", "Complain" }));
        prathapicatBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapicatBoxActionPerformed(evt);
            }
        });

        prathapirating2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating2MouseClicked(evt);
            }
        });
        prathapirating2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapirating2ActionPerformed(evt);
            }
        });

        prathapirating3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating3MouseClicked(evt);
            }
        });
        prathapirating3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapirating3ActionPerformed(evt);
            }
        });

        prathapirating4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating4MouseClicked(evt);
            }
        });
        prathapirating4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapirating4ActionPerformed(evt);
            }
        });

        prathapirating5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating5MouseClicked(evt);
            }
        });
        prathapirating5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapirating5ActionPerformed(evt);
            }
        });

        prathapirating1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating1MouseClicked(evt);
            }
        });
        prathapirating1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapirating1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prathapijLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(prathapijLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(prathapicusTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(prathapicatBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(prathapirating1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(prathapirating2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92)
                                        .addComponent(prathapirating3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addComponent(prathapirating4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(prathapirating5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(prathapijLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prathapijLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(prathapijScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(prathapijButton1)
                        .addGap(75, 75, 75)
                        .addComponent(prathapijButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(prathapijLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prathapijLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prathapijLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prathapicusTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prathapijLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prathapicatBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prathapijLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prathapirating4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(prathapirating5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prathapirating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prathapirating2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prathapirating3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prathapijLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(prathapijScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prathapijButton1)
                    .addComponent(prathapijButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prathapicusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapicusTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapicusTxtActionPerformed

    private void prathapicusTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prathapicusTxtFocusGained
      /*   if(textField1.getText().trim().toLowerCase().equals("enter your customer id"))
         {
             textField1.setText("");
             textField1.setForeground(Color.black);
         }*/
    }//GEN-LAST:event_prathapicusTxtFocusGained

    private void prathapicusTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_prathapicusTxtFocusLost
        /* if(textField1.getText().trim().equals("")||
                 textField1.getText().trim().toLowerCase().equals("Eter Yout Customer ID"));
         {
             textField1.setText("Enter Your Customer ID");
             textField1.setForeground(new Color(153,153,153));
         }
          */   
    }//GEN-LAST:event_prathapicusTxtFocusLost

    private void optionTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_optionTxtFocusGained
         //if(jTextArea1.getText().trim().toLowerCase().equals("say something....."))
         //{
              //jTextArea1.setText("");
              //jTextArea1.setForeground(Color.black);
         //}
    }//GEN-LAST:event_optionTxtFocusGained

    private void optionTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_optionTxtFocusLost
          //if(jTextArea1 .getText().trim().equals("")||
                 // jTextArea1.getText().trim().toLowerCase().equals(" say something....."));
         //{
             // jTextArea1.setText("Say Something.....");
             // jTextArea1.setForeground(new Color(153,153,153));
         //}
    }//GEN-LAST:event_optionTxtFocusLost

    private void prathapijButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapijButton2MouseClicked
         main_page mp = new main_page();
         mp.setVisible(true);
         mp.pack();
         mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.dispose();
    }//GEN-LAST:event_prathapijButton2MouseClicked

    private void prathapirating2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating2MouseClicked
      if(prathapirating2.getBackground() == (yellow)) {
            prathapirating2.setBackground(myWhite);
            prathapirating3.setBackground(myWhite);
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 1;
        }
        else {
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 2;
        }
    }//GEN-LAST:event_prathapirating2MouseClicked

    private void prathapirating3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating3MouseClicked
      if(prathapirating3.getBackground() == (yellow)) {
            prathapirating3.setBackground(myWhite);
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 2;
        }
        else {
              prathapirating3.setBackground(Color.yellow);
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 3;
        }
    }//GEN-LAST:event_prathapirating3MouseClicked

    private void prathapirating4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating4MouseClicked
        if(prathapirating4.getBackground() == (yellow)) {
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 3;
        }
        else {
              prathapirating4.setBackground(Color.yellow);
              prathapirating3.setBackground(Color.yellow);
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 4;
        }
    }//GEN-LAST:event_prathapirating4MouseClicked

    private void prathapirating5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating5MouseClicked
        if(prathapirating5.getBackground() == (yellow)) {
            prathapirating5.setBackground(myWhite);
            rating = 4;
        }
        else {
              prathapirating5.setBackground(Color.yellow);
              prathapirating4.setBackground(Color.yellow);
              prathapirating3.setBackground(Color.yellow);
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 5;
        }
    }//GEN-LAST:event_prathapirating5MouseClicked

    private void prathapirating1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating1MouseClicked
        if(prathapirating1.getBackground() == (yellow)) {
            prathapirating1.setBackground(myWhite);
            prathapirating2.setBackground(myWhite);
            prathapirating3.setBackground(myWhite);
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 0;
        }
        else {
              prathapirating1.setBackground(Color.yellow);
              rating = 1;
        }
                
    }//GEN-LAST:event_prathapirating1MouseClicked

    private void prathapijButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapijButton1ActionPerformed
        if(prathapicusTxt.getText().toString().equals("")||prathapicusTxt.getText() == null){
            JOptionPane.showMessageDialog(frame, "Customer ID Required!");
        }else if(prathapicatBox.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(frame, "Please Select Category!");
        }else if(rating == 0){
            JOptionPane.showMessageDialog(frame, "Please Select Rating!");
        }else{
            Connection connection;
            PreparedStatement preparedStatement;
		
		try {
			connection = FBDBConnect.getDBConnection();
			
                        //insert value
                        preparedStatement = connection.prepareStatement("insert into feedback  (custId, category, rating, options) VALUES (?, ?, ?, ?)");
                        preparedStatement.setInt(1, Integer.parseInt(prathapicusTxt.getText().toString()));
                        preparedStatement.setString(2, prathapicatBox.getSelectedItem().toString());
                        preparedStatement.setInt(3, rating);
                        preparedStatement.setString(4, optionTxt.getText().toString());
                        preparedStatement.execute();
                        preparedStatement.close();
                        connection.close();
                        
                        prathapirating1.setBackground(myWhite);
                        prathapirating2.setBackground(myWhite);
                        prathapirating3.setBackground(myWhite);
                        prathapirating4.setBackground(myWhite);
                        prathapirating5.setBackground(myWhite);
                        
                        prathapicusTxt.setText("");
                        prathapicatBox.setSelectedIndex(0);
                        optionTxt.setText("");
                        rating = 0;
                        
                        JOptionPane.showMessageDialog(frame, "Send Feedback Successful!");
                        
                    }catch (ClassNotFoundException | SQLException  e) {
                    System.out.println(e.getMessage());
		}
        }
    }//GEN-LAST:event_prathapijButton1ActionPerformed

    private void prathapicatBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapicatBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapicatBoxActionPerformed

    private void prathapirating1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapirating1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapirating1ActionPerformed

    private void prathapirating5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapirating5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapirating5ActionPerformed

    private void prathapirating4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapirating4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapirating4ActionPerformed

    private void prathapirating3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapirating3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapirating3ActionPerformed

    private void prathapicusTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prathapicusTxtKeyReleased
        try {
            x = Integer.parseInt(prathapicusTxt.getText());
        } catch (NumberFormatException nfe) {
            prathapicusTxt.setText("");
        }
    }//GEN-LAST:event_prathapicusTxtKeyReleased

    private void prathapirating2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapirating2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapirating2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enter_feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enter_feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enter_feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enter_feedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enter_feedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea optionTxt;
    private javax.swing.JComboBox<String> prathapicatBox;
    private java.awt.TextField prathapicusTxt;
    private javax.swing.JButton prathapijButton1;
    private javax.swing.JButton prathapijButton2;
    private javax.swing.JLabel prathapijLabel1;
    private javax.swing.JLabel prathapijLabel2;
    private javax.swing.JLabel prathapijLabel3;
    private javax.swing.JLabel prathapijLabel4;
    private javax.swing.JLabel prathapijLabel5;
    private javax.swing.JScrollPane prathapijScrollPane1;
    private javax.swing.JToggleButton prathapirating1;
    private javax.swing.JToggleButton prathapirating2;
    private javax.swing.JToggleButton prathapirating3;
    private javax.swing.JToggleButton prathapirating4;
    private javax.swing.JToggleButton prathapirating5;
    // End of variables declaration//GEN-END:variables
}
