package view;


import util.FBDBConnect;
import java.awt.Color;
import static java.awt.Color.yellow;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SRI
 */
public class update_feedback_new extends javax.swing.JFrame {

    int feedbackId,rating=0;
    
    Color myWhite = new Color(240, 240, 240);
    
    JFrame frame;
    
    /**
     * Creates new form update_feedback_new
     */
    public update_feedback_new(int id,String category,String feedback,int rating) {
        initComponents();
        
        feedbackId = id;
        
        prathapicatBox1.setSelectedItem(category);
        
        optionTxt.setText(feedback);
        
        this.rating = rating;
        
        if(rating==1){
            prathapirating1.setBackground(Color.yellow);
        }else if(rating==2){
            prathapirating2.setBackground(Color.yellow);
            prathapirating1.setBackground(Color.yellow);
        }else if(rating==3){
            prathapirating3.setBackground(Color.yellow);
            prathapirating2.setBackground(Color.yellow);
            prathapirating1.setBackground(Color.yellow);
        }else if(rating==4){
            prathapirating4.setBackground(Color.yellow);
            prathapirating3.setBackground(Color.yellow);
            prathapirating2.setBackground(Color.yellow);
            prathapirating1.setBackground(Color.yellow);
        }else if(rating==5){
            prathapirating5.setBackground(Color.yellow);
            prathapirating4.setBackground(Color.yellow);
            prathapirating3.setBackground(Color.yellow);
            prathapirating2.setBackground(Color.yellow);
            prathapirating1.setBackground(Color.yellow);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        prathapijLabel1 = new javax.swing.JLabel();
        prathapijButton2 = new javax.swing.JButton();
        prathapijButton1 = new javax.swing.JButton();
        prathapicatBox1 = new javax.swing.JComboBox<>();
        prathapijLabel7 = new javax.swing.JLabel();
        prathapijLabel8 = new javax.swing.JLabel();
        prathapirating1 = new javax.swing.JToggleButton();
        prathapirating2 = new javax.swing.JToggleButton();
        prathapirating3 = new javax.swing.JToggleButton();
        prathapirating4 = new javax.swing.JToggleButton();
        prathapirating5 = new javax.swing.JToggleButton();
        prathapijScrollPane2 = new javax.swing.JScrollPane();
        optionTxt = new javax.swing.JTextArea();
        prathapijLabel9 = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Select Category :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prathapijLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        prathapijLabel1.setText(" UPDATE FEEDBACK");

        prathapijButton2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton2.setForeground(new java.awt.Color(28, 47, 123));
        prathapijButton2.setText(" UPDATE FEEDBACK");
        prathapijButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prathapijButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapijButton2ActionPerformed(evt);
            }
        });

        prathapijButton1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijButton1.setText(" MAIN MENU");
        prathapijButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapijButton1MouseClicked(evt);
            }
        });
        prathapijButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapijButton1ActionPerformed(evt);
            }
        });

        prathapicatBox1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        prathapicatBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "~ Select ~", "Suggestion", "Something is not correct", "Complain" }));
        prathapicatBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapicatBox1ActionPerformed(evt);
            }
        });

        prathapijLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel7.setText(" Select Category :");

        prathapijLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel8.setText("Rating :");

        prathapirating1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating1MouseClicked(evt);
            }
        });

        prathapirating2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating2MouseClicked(evt);
            }
        });

        prathapirating3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating3MouseClicked(evt);
            }
        });

        prathapirating4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating4MouseClicked(evt);
            }
        });
        prathapirating4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prathapirating4ActionPerformed(evt);
            }
        });

        prathapirating5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prathapirating5MouseClicked(evt);
            }
        });

        optionTxt.setColumns(20);
        optionTxt.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        optionTxt.setRows(5);
        optionTxt.setText(" .");
        prathapijScrollPane2.setViewportView(optionTxt);

        prathapijLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        prathapijLabel9.setText("Opinion :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(prathapijLabel9)
                                    .addComponent(prathapijLabel8)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(prathapijLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(prathapirating1)
                                            .addGap(70, 70, 70)
                                            .addComponent(prathapirating2))
                                        .addComponent(prathapijLabel7))
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(32, 32, 32)
                                            .addComponent(prathapicatBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(45, 45, 45)
                                            .addComponent(prathapirating3)
                                            .addGap(87, 87, 87)
                                            .addComponent(prathapirating4)
                                            .addGap(87, 87, 87)
                                            .addComponent(prathapirating5))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(prathapijScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(prathapijButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(prathapijButton1)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prathapijLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prathapijLabel7)
                    .addComponent(prathapicatBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(prathapijLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prathapirating1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prathapirating5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prathapirating2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(prathapirating4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(prathapirating3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(prathapijLabel9)
                .addGap(18, 18, 18)
                .addComponent(prathapijScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prathapijButton2)
                    .addComponent(prathapijButton1))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prathapijButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapijButton2ActionPerformed
        if(prathapicatBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(frame, "Please Select Category!");
        }else if(rating == 0){
            JOptionPane.showMessageDialog(frame, "Please Select Rating!");
        }else{
            Connection connection;
            PreparedStatement preparedStatement;
		
		try {
			connection = FBDBConnect.getDBConnection();
			
                        //insert value
                        preparedStatement = connection.prepareStatement("UPDATE feedback  SET category=?, rating=?, options=? WHERE feedbackId=?");
                        preparedStatement.setString(1, prathapicatBox1.getSelectedItem().toString());
                        preparedStatement.setInt(2, rating);
                        preparedStatement.setString(3, optionTxt.getText().toString());
                        preparedStatement.setInt(4, feedbackId);
                        preparedStatement.execute();
                        preparedStatement.close();
                        connection.close();
                        
                        prathapirating1.setBackground(myWhite);
                        prathapirating2.setBackground(myWhite);
                        prathapirating3.setBackground(myWhite);
                        prathapirating4.setBackground(myWhite);
                        prathapirating5.setBackground(myWhite);
                        
                        prathapicatBox1.setSelectedIndex(0);
                        optionTxt.setText("");
                        rating = 0;
                        
                        JOptionPane.showMessageDialog(frame, "Feedback Update Successful!");
                        
                        JFrame frame = new update_feedback();
            
                        frame.setVisible(true);
                        dispose();
                        
                    }catch (ClassNotFoundException | SQLException  e) {
                    System.out.println(e.getMessage());
		}
        }
    }//GEN-LAST:event_prathapijButton2ActionPerformed

    private void prathapijButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapijButton1MouseClicked
         main_page mp = new main_page();
         mp.setVisible(true);
         mp.pack();
         mp.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         this.dispose();
    }//GEN-LAST:event_prathapijButton1MouseClicked

    private void prathapijButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapijButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapijButton1ActionPerformed

    private void prathapirating1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating1MouseClicked
        if(prathapirating1.getBackground() == (yellow)) {
            prathapirating1.setBackground(myWhite);
            prathapirating2.setBackground(myWhite);
            prathapirating3.setBackground(myWhite);
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 0;
        }
        else {
              prathapirating1.setBackground(Color.yellow);
              rating = 1;
        }
    }//GEN-LAST:event_prathapirating1MouseClicked

    private void prathapirating2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating2MouseClicked
        if(prathapirating2.getBackground() == (yellow)) {
            prathapirating2.setBackground(myWhite);
            prathapirating3.setBackground(myWhite);
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 1;
        }
        else {
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 2;
        }
    }//GEN-LAST:event_prathapirating2MouseClicked

    private void prathapirating3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating3MouseClicked
        if(prathapirating3.getBackground() == (yellow)) {
            prathapirating3.setBackground(myWhite);
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 2;
        }
        else {
              prathapirating3.setBackground(Color.yellow);
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 3;
        }
    }//GEN-LAST:event_prathapirating3MouseClicked

    private void prathapirating4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating4MouseClicked
        if(prathapirating4.getBackground() == (yellow)) {
            prathapirating4.setBackground(myWhite);
            prathapirating5.setBackground(myWhite);
            rating = 3;
        }
        else {
              prathapirating4.setBackground(Color.yellow);
              prathapirating3.setBackground(Color.yellow);
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 4;
        }
    }//GEN-LAST:event_prathapirating4MouseClicked

    private void prathapirating5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prathapirating5MouseClicked
        if(prathapirating5.getBackground() == (yellow)) {
            prathapirating5.setBackground(myWhite);
            rating = 4;
        }
        else {
              prathapirating5.setBackground(Color.yellow);
              prathapirating4.setBackground(Color.yellow);
              prathapirating3.setBackground(Color.yellow);
              prathapirating2.setBackground(Color.yellow);
              prathapirating1.setBackground(Color.yellow);
              rating = 5;
        }
    }//GEN-LAST:event_prathapirating5MouseClicked

    private void prathapicatBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapicatBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapicatBox1ActionPerformed

    private void prathapirating4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prathapirating4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prathapirating4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_feedback_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_feedback_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_feedback_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_feedback_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_feedback_new(0,"","",0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea optionTxt;
    private javax.swing.JComboBox<String> prathapicatBox1;
    private javax.swing.JButton prathapijButton1;
    private javax.swing.JButton prathapijButton2;
    private javax.swing.JLabel prathapijLabel1;
    private javax.swing.JLabel prathapijLabel7;
    private javax.swing.JLabel prathapijLabel8;
    private javax.swing.JLabel prathapijLabel9;
    private javax.swing.JScrollPane prathapijScrollPane2;
    private javax.swing.JToggleButton prathapirating1;
    private javax.swing.JToggleButton prathapirating2;
    private javax.swing.JToggleButton prathapirating3;
    private javax.swing.JToggleButton prathapirating4;
    private javax.swing.JToggleButton prathapirating5;
    // End of variables declaration//GEN-END:variables
}
